### ISSUE TITLE
Moving ggtags from C/C++ to Project Managment/Programming

### ISSUE THREAD

**Issue by Gleek** [emacs-tw/awesome-emacs#100]
Gnu Global supports 6 languages by inbuilt parser and more than 25 languages by Pygments + Exuberant Ctags plug-in parser. I don't think it should just be kept in C/C++ category, when it can support most of the languages listed in the document.

Reference: [GNU Global website](http://www.gnu.org/software/global/)

**Comment by agsdot** [comment]
Thanks for the feedback. Change made in [#194](https://github.com/emacs-tw/awesome-emacs/pull/194).

Closing issue.
