### ISSUE TITLE
org-protocol-capture-html

### ISSUE THREAD

**Issue by alphapapa** [emacs-tw/awesome-emacs#105]
I think this would fit under the Org-mode heading.

https://github.com/alphapapa/org-protocol-capture-html

**Comment by darrylhebbes** [comment]
Please fork the repo, add it and make a pull request.

**Comment by alphapapa** [comment]
Thanks for your reply.  That seems like a lot of effort to go to for a one-line addition that the repo maintainer could make and push with Emacs and Magit in a few seconds...  :)

**Comment by kuanyui** [comment]
No, because I'm too lazy =w=
And I have not used this package, so I won't recommend this by myself.

**Comment by agsdot** [comment]
Addressed issue in #197.
