### ISSUE TITLE
Dead link to EmacsMinimap

### ISSUE THREAD

**Issue by apofiget** [emacs-tw/awesome-emacs#170]
Hi, there!
You have dead link to EmacsMinimap - https://github.com/dustinlacewell/emacs-minimap

**Comment by kuanyui** [comment]
Feel free to make PR :)

**Comment by agsdot** [comment]
@kuanyui, this issue looks like it can be closed. It was addressed by b058bcb4.

**Comment by kuanyui** [comment]
Thanks!
