### ISSUE TITLE
makefile support

### ISSUE THREAD

**Issue by LinFelix** [emacs-tw/awesome-emacs#188]
There is no section for makefiles with the packages supporting  makefiles listed.

**Comment by agsdot** [comment]
@LinFelix, do you have any package suggestions?

**Comment by LinFelix** [comment]
helm-make, makefile-executor, makefile-runner
and basic-c-compile is for Makefiles but most useful with C.

There is also not a lot for cmake in this repo.
cmake-font-lock (advanced highlight support), cmake-ide, cmake-mode, cmake-project and company-cmake (which is maybe more company than cmake).

**Comment by agsdot** [comment]
Thanks @LinFelix . There's several paths to move forward on this issue:

1) You can create a pull request and add them to awesome-emacs. I'd suggest creating a new category and then running gen-toc.el to update the table of content links.

2) Another option, can you update this Issue thread with the URL's to those listed make/cmake resources, and I can add and update awesome-emacs.

Thanks for your contributions!

**Comment by agsdot** [comment]
Makefile section added in [PR #209](https://github.com/emacs-tw/awesome-emacs/pull/209).

Closing issue.
