### ISSUE TITLE
Would like to see: org-trello

### ISSUE THREAD

**Issue by mickael-kerjean** [emacs-tw/awesome-emacs#192]
It's great to see all those awesome plugins but I recently found out org-trello which is awesome and don't appear here.

It basically allow you to collaborate with non emacs user on your todos using trello. I believe it should definitely appear under the org headline

**Comment by agsdot** [comment]
Thanks for the suggestion @mickael-kerjean , just added it in [PR# 193](https://github.com/emacs-tw/awesome-emacs/pull/193).
