### ISSUE TITLE
Elbank is not maintained anymore

### ISSUE THREAD

**Issue by Fuco1** [emacs-tw/awesome-emacs#265]
Do we want to have unmaintained packages on the list?

Elbank was recently announced to be deprecated in favour of ledger-mode (iow the author returned back to using ledger).

cc @NicolasPetton What do you think?

**Comment by agsdot** [comment]
This is a great question @Fuco1 .  What are your thoughts @NicolasPetton? If the item is removed at the very least, the package is acknowledged in the git log / history. So people can still have a reference to it.

I've been contemplating the question you posed Fuco1 about "Do we want to have unmaintained packages on the list?" [grizzl](https://github.com/grizzl/grizzl) is deprecated, and there are several projects linked to here on awesome-emacs that are no longer actively maintained on github (the whole github -> gitlab migration being one of the main causes, with microsoft's recently announced acquisition of github).

**Comment by agsdot** [comment]
Several projects are now maintained on gitlab rather than github. When I get time, I would like to update those links, or if anyone else would like to update those URL's a PR is most welcome.

**Comment by agsdot** [comment]
@Fuco1, thank you for creating this issue. Several things have been done, elbank, an unmaintained project, and two grizzl deprecated projects have been removed. This was accomplished in [PR #285](https://github.com/emacs-tw/awesome-emacs/pull/285).

Closing this Issue #265.

**Comment by agsdot** [comment]
@Fuco1, to directly answer your question: "Do we want to have unmaintained packages on the list?"

-  If a project is incredibly popular and is unmaintained, I'd like to keep it listed here.

-  If a project is 1) unmaintained and 2) deprecated, let's remove it. The git log will keep a track record of the packages that have come and gone. I think this provides a nice compromise.

Thank you once again, and have a great day.
