### ISSUE TITLE
The list is too long, lots of unmaintained/old code.

### ISSUE THREAD

**Issue by Fuco1** [emacs-tw/awesome-emacs#273]
From https://github.com/sindresorhus/awesome/blob/master/awesome.md

> Research if the stuff you're including is actually awesome. Only put stuff on the list that you or another contributor can personally recommend. *You should rather leave stuff out than include too much.*

Emph. mine.  There are things like `popup-kill-ring` on this list.  The last release is from 2013 which is just a copy/paste from Emacs Wiki.  It has less than 3000 downloads on MELPA.  Is it really awesome?  Does it even work?

I've just singled out this package because it was the first I randomly landed at, not on purpose.  I've never used it.  But maybe we should actually "curate" the list instead of just throwing in everything.

Opinions?

**Comment by kuanyui** [comment]
> Also if you look at the order, for example in `Keys Cheat Sheet` section. discover.el has 6800 downloads while which-key has over 350000. Why is it 5th on the list?

Feel free to send a PR!
 
> I get it that newer packages will not have so many downloads, but discover.el (latest release) is from at least 2014. It didn't get a lot of traction...

Feel free to send a PR!
