### ISSUE TITLE
Add more prose related stuff (not just text in general), and maybe a section just for it

### ISSUE THREAD

**Issue by mrbig033** [emacs-tw/awesome-emacs#284]
I'm talking about stuff directly related with the task of writing prose, **not code**.

For example:

* [Flyspell](https://www.emacswiki.org/emacs/FlySpell)
* [Olivetti](https://github.com/rnkn/olivetti)
* [Auto-capitalize](https://www.emacswiki.org/emacs/auto-capitalize.el)
* [Aggressive fill-paragraph](https://github.com/davidshepherd7/aggressive-fill-paragraph-mode)
* [Langtool](https://github.com/mhayashi1120/Emacs-langtool)
* [Writegood](https://github.com/btford/write-good)
* [Pabbrev](https://github.com/phillord/pabbrev)
* [Fountain](https://github.com/rnkn/fountain-mode)
* [nov.el](https://github.com/wasamasa/nov.el)
* [adoc-mode](https://github.com/sensorflo/adoc-mode)
* [Pandoc](https://pandoc.org/)

**Comment by kuanyui** [comment]
Needn't to ask, just open a section if anyone like. :)
