### ISSUE TITLE
Cleanup Starter Kit and Noteworthy Configurations Section

### ISSUE THREAD

**Issue by agsdot** [emacs-tw/awesome-emacs#338]
Hello @coldnew and @kuanyui,

Here are some thoughts as I did a recent Pull Request https://github.com/emacs-tw/awesome-emacs/pull/337 in which I lowered the priority of some (inactive) Starter Kit packages and also as I thought about @coldnew 's PR for https://github.com/emacs-tw/awesome-emacs/pull/336 in removing a no longer developed emacs configuration. I was wondering if you could share some feedback. 

General Issues
  - Items in the Starter Kit section should be reordered based on "popularity" relevance and how much they are actively being developed.
  - Also, https://github.com/hlissner/doom-emacs should probably go in the Starter Kit section as it is often compared to spacemacs (evil mode based config, etc).

Proposal to remove "Noteworthy Configuration" Section
- In addition, after noticing issues with https://github.com/emacs-tw/awesome-emacs/pull/336, many of the noteworthy configurations are listed on https://github.com/caisah/emacs.dz --only a few are not cross-listed on both. Also, caisah/emacs.dz gives a much more informative and useful description of noteworthy configuations. I propose that awesome-emacs remove the Noteworthy Configuration section and consolidate on the Starter Kits section.
- I've been wondering for awhile under which category to add the package https://github.com/plexus/chemacs, it could have gone under either Starter Kit or Noteworthy Configurations. Noteworthy Configurations is already taken care of by caisah's emacs.dz, Doom Emacs should be moved to Starter Kits
- Modify the "Starter Kit" section to have a link to personal "noteworthy configurations" on caisah emacs.dz and also include a link to the really novel chemacs package.

**Comment by kuanyui** [comment]
@agsdot Hi thanks, I personally think that remove "Noteworthy Configuration" section is a pretty awesome idea! I think it's pretty good idea to just give it a link to [caisah/emacs.dz]() just like the format of [Programming Language / Haskell](https://github.com/emacs-tw/awesome-emacs#haskell).

**Comment by agsdot** [comment]
Closing Issue. PR #339 addressed items brought up in this Issue thread.
