### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by E3D3** [emacs-tw/awesome-emacs#423]
Maybe [emacs-distribution](https://www.emacswiki.org/emacs/emacs-distribution) is something to add.
>  Simplifies running Emacs from an alternative $HOME in order to
> experiment with alternative configurations without affecting your
> default (~/.emacs.d) config.

**Comment by agsdot** [comment]
That resource was last edited on emacswiki in 2014.

Seems like chemacs2 is more commonly referenced (e.g. by @hlissner himself on reddit: https://www.reddit.com/r/emacs/comments/tj0na6/comment/i1hes3p/) .

**Comment by E3D3** [comment]
I don't think that emacswiki updates are always a good indicator for the value of its subject, nor how often sourcecode updates, but I'll try chemacs2 to compare emacs-distribution, that indeed has some trouble with $HOME. Thanks for the reply, and awesome emacs list.
