### ISSUE TITLE
Where to categorize symon?

### ISSUE THREAD

**Issue by agsdot** [emacs-tw/awesome-emacs#75]
Hey @emacs-tw team, was wondering where and how you'd categorize [symon](https://github.com/zk-phi/symon/)? A "tiny graphical system monitor"

A category already present? Or another one, such as "Utilities" (which seems kind of ambiguous/vague), or something alluding to Operating System Integration. Ideas?

**Comment by kuanyui** [comment]
Indeed it seems that no existed category suitable... Feel free to create new category if needs :)

**Comment by agsdot** [comment]
Looked over the TOC again before doing a pull request, noticed category for Integration.  Put a sub category of Operating System under it. Hope that fits, otherwise, can update the pull request.

**Comment by kuanyui** [comment]
Done~
