### ISSUE TITLE
missing a license

### ISSUE THREAD

**Issue by arthurvr** [emacs-tw/awesome-emacs#80]
This repo misses a license. You can use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by agsdot** [comment]
Wow, what a great question. @arthurvr and @Superbil and @kuanyui and the whole #emacs-tw team, how do you choose a good license for something like this (a curated awesome list, or a piece of shared documentation-- a la wiki, or other form of documentation).

MIT? GPL? BSD? Apache? The typical software licenses?

Or something used for text, such as Creative Common's license (developed and created at [Stanford Law](https://www.law.stanford.edu/) ).  Or like wikipedia's [Creative Commons Attribution-ShareAlike License](https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License).

@sindresorhus license as listed at [awesome#license](https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License), lists it as public domain and as having waived "To the extent possible under law... all copyright and related or neighboring rights to this work." How formal of a license is this? How much clarity or ambiguity is in this license? I wonder.

Anyhow, @arthurvr & @kuanyui and the whole #emacs-tw team, I eagerly await to see how a license is actually chosen for this project.

**Comment by kuanyui** [comment]
Thank you for your reminding. ˊ・w・ˋ
However, I'm not sure which license won't enrage the existed contributor.
In my opinion, I think Public Domain is suitable for the list like this.

**Comment by agsdot** [comment]
Hey @Kuanyui, thanks for the quick reply.

Hum...what does " for your reminding. ˊ・w・ˋ" mean? Who is ˊ・w・ˋ ?

Lol. Your words about what "won't enrage existed contributors" amuses me. Why would I or other contributors to a this awesome-lists be "enrage(d)"?

An Awesome-List seems like another type of wiki format (a la dokuwiki, mediawiki, etc) with the only difference that their is a main facilitator to curate the documentation (the project manager(s) that facilitate the git pull requests).  What is so special about that?

A public domain mention seems honestly quite ambiguous. 

There are licenses such as Apache, BSD, MIT, etc. But also some licenses with as stupid a name as the WTFPL -- a license that honestly should have a much more ...ahem... polite naming. 

Honestly though,  public domain could use some clarification.  Public domain for what country/region? North America? Asia? Europe? Africa? South America? You get my point.

As to the specific wording on the other referenced to awesome-list "To the extent possible under law, Sindre Sorhus has waived all copyright and related or neighboring rights to this work."  The following questions can be posed.

  - "under law" -- which countries/regions law(s)
  - What are the "all copyright(s) ...(and) neighboring rights" that the individual is alluding to?

**Comment by agsdot** [comment]
On further examination of the icon/logo @sindresorhus placed on his [site](https://github.com/sindresorhus/awesome)

[![CC0](http://i.creativecommons.org/p/zero/1.0/88x31.png)](http://creativecommons.org/publicdomain/zero/1.0/)

after examining the underlying hyperlink, I noticed that it links to a license from the [Creative Commons](https://creativecommons.org/).  

I think that it would be "awesome" (yes, the cheesy pun was indeed intentional) that a license indeed be placed on the [awesome-emacs](https://github.com/emacs-tw/awesome-emacs) awesome list, and where it is placed or indicated, it explicitly states something about the license.

Rather than just saying "public domain" or merely linking to a png file for public domain, it explicitly states in writing something along the lines of "This is licensed under a creative commons compatible license for...(x/y/z, whether it be public domain or something else)."  After seeing that, then any individual can read up and goto the Creative Common's website and research and readup on all the legal diction/jargon that [Stanford's](https://www.stanford.edu/) (Lawrence Lessig)[https://en.wikipedia.org/wiki/Lawrence_Lessig] created in setting up the license(s) and the CC foundation.  I'm sure Lessig researched stuff such as "under law" as pertaining to multiple countries and global boundaries.

Thanks @kuanyui! And have a great day! I hope all is going splendid in Taiwan and in East Asia!

**Comment by kuanyui** [comment]
> Hum...what does " for your reminding. ˊ・w・ˋ" mean? Who is ˊ・w・ˋ ?

[ˊ・ω・ˋ](https://www.google.com.tw/search?q=nyoron&biw=1366&bih=700&source=lnms&tbm=isch&sa=X&ei=usScVb6CJNGA8QWq7InoCA&ved=0CAgQ_AUoAQ)

> Lol. Your words about what "won't enrage existed contributors" amuses me. Why would I or other contributors to a this awesome-lists be "enrage(d)"? The thought honestly is quite comical and amusing.

Maybe I'm too paranoid, after seeing some bad things happened in FLOSS community (at least in Taiwan) -- that don't think everyone in FLOSS community is really that......kind or open-minded. I'm just don't know if there anyone will be angry when they seeing the project change license after their contributions.

It's a good thing that knowing this worry can amuse somebody, maybe I don't need to think that much in this issue. ˊ・ω・ˋ

----

Now... just take Public Domain? I think this license is so simple that doesn't need further explanation like "This is licensed under a creative commons compatible license..."

>[![CC0](http://i.creativecommons.org/p/zero/1.0/88x31.png)](http://creativecommons.org/publicdomain/zero/1.0/)
To the extent possible under law, [emacs.tw](https://github.com/emacs-tw) has waived all copyright and related or neighboring rights to this work.

**Comment by sindresorhus** [comment]
You could always go with CC0 for clarity: https://creativecommons.org/publicdomain/zero/1.0/

**Comment by strugee** [comment]
> I'm just don't know if there anyone will be angry when they seeing the project change license after their contributions.

Technically, you actually can't change the license under which other people have contributed, since they still hold copyright. I would just ask - it's polite _and_ legal.

**Comment by agsdot** [comment]
@sindresorhus, thanks for your input. You're an awesome #javascript #expert and facilitator of many great #awesome-pages. Thanks for hosting so many of these great projects on github and also being a great #js leader.

@struggee, that's a great idea. As of July 8, 2015, there are "only" 42 contributors. We should "ask....polite(ly)" as you suggest. Seems appropriate.

@kuanyui, within a month or two, I can put in a PR with a blank License.md file with the "License To Be Determined" as a pull request. On the PR, I'll solicit feedback from the as of yet 42 contributors as to an appropriate license, as per @strugee's suggestion, and after hearing back from "the people(s)", I'll change the text of the License.md (lol, or rather License.org) file to have the content of the license.

Tentatively now, I'm thinking the License.org file should follow along @sindresorhus 's suggestion. @kuanyui , I'm fine with my contributions to [emacs-tw/awesome-emacs](https://github.com/emacs-tw/awesome-emacs/) being put under pretty much any license (CC, MIT, GPL, etc, whatever...) as long as their is clarity to the license and it does not have ambiguity.

**Comment by Superbil** [comment]
@agsdot Thank for your help. I will chose CC0 for awesome-emacs.

@kuanyui In many cases CC0 is a good choice, then I can explain it to you next time.
