### ISSUE TITLE
Link is broken for Xrefactory

### ISSUE THREAD

**Issue by nloyola** [emacs-tw/awesome-emacs#83]
Link gives `This web page is not available`.

**Comment by xfq** [comment]
Cannot reproduce on my machine:

![image](https://cloud.githubusercontent.com/assets/2863444/8893680/2c9a7ce8-33cd-11e5-9c21-a828f46a1ce9.png)

**Comment by nloyola** [comment]
I tried it both with Chrome and Firefox and I still get an `This web page is not available`. 

Even `ping` does not work: I get `ping: unknown host www.xref.sk`.

![xrefactory_404](https://cloud.githubusercontent.com/assets/334607/8894588/2d5e4f6e-3379-11e5-9cb7-b3adfde4deeb.png)

**Comment by xuchunyang** [comment]
The page http://www.xref.sk/xrefactory/emacs.html is fine here, and the site is up also according to http://downforeveryoneorjustme.com/http://www.xref.sk/xrefactory/emacs.html.

**Comment by nloyola** [comment]
What IP address does `www.xref.sk` resolve to? Let me try connecting directly to the IP address.

**Comment by xuchunyang** [comment]
```
~ % host www.xref.sk
www.xref.sk is an alias for www.xrefactory.com.
www.xrefactory.com is an alias for xrefactory.com.
xrefactory.com has address 37.59.38.122
xrefactory.com mail is handled by 10 xrefactory.com.
~ % ping -c 1 www.xref.sk
PING xrefactory.com (37.59.38.122): 56 data bytes
64 bytes from 37.59.38.122: icmp_seq=0 ttl=49 time=386.331 ms

--- xrefactory.com ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 386.331/386.331/386.331/0.000 ms
```

**Comment by nloyola** [comment]
I did a *whois* lookup and it gave me a DNS entry of `ns1.xrefactory.com`. If I point Chrome there I get the web page you screenshotted above.

So this works:

http://ns1.xrefactory.com/about.html

**Comment by nloyola** [comment]
This also works: http://www.xrefactory.com/about.html.

The link should be changed to this I think.
